---

- name: Add phusion passenger repo apt key
  apt_key: keyserver=keyserver.ubuntu.com id=16378A33A6EF16762922526E561F9B9CAC40B2F7
  when: nginx_manage_repo and nginx_package_source == 'passenger'

- name: Add phusion passenger repo to sources list
  apt_repository: repo="deb {{ nginx_passenger_repo }}" state=present
  when: nginx_manage_repo and nginx_package_source == 'passenger'
  register: passenger_repo
  notify: Update nginx apt cache

- name: Add nginx repo apt key
  apt_key: keyserver=keyserver.ubuntu.com id=573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
  when: nginx_manage_repo and nginx_package_source|match('nginx|nginx-stable|nginx-mainline')

- name: Add nginx repo to sources list
  apt_repository: repo="deb {{ nginx_repo }}" state=present
  when: nginx_manage_repo and nginx_package_source|match('nginx|nginx-stable')
  register: default_repo
  notify: Update nginx apt cache

- name: Add nginx mainline repo to sources list
  apt_repository: repo="deb {{ nginx_mainline_repo }}" state=present
  when: nginx_manage_repo and nginx_package_source == 'nginx-mainline'
  register: mainline_repo
  notify: Update nginx apt cache

- meta: flush_handlers
  when: default_repo|changed or mainline_repo|changed or passenger_repo|changed

- name: Install phusion passenger prerequisites
  apt: name={{ item }} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
  when: nginx_manage_repo and nginx_package_source == 'passenger'

- name: Install phusion passenger
  apt: name=passenger state=present
  when: nginx_manage_repo and nginx_package_source == 'passenger'

- name: Install nginx package
  apt:
    name: "{{ nginx_package_name }}={{ nginx_version|default('*') }}"
    state: present
